spring.application.name=AquaBalance
server.port=${PORT:8084}

spring.datasource.url=jdbc:postgresql://ep-autumn-recipe-aqvjhsu1-pooler.c-8.us-east-1.aws.neon.tech/neondb?sslmode=require
spring.datasource.username=neondb_owner
spring.datasource.password=npg_9olzP3wMacTJ
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.datasource.hikari.maximum-pool-size=5

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=${SPRING_MAIL_USERNAME:yudiguayara@gmail.com}
spring.mail.password=${SPRING_MAIL_PASSWORD:kutjqstavxqmouhk}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true

notificacion.email.destinatario=${NOTIFICACION_EMAIL_DESTINATARIO:yudiguayara@gmail.com}
notificacion.email.habilitado=true