spring.application.name=AquaBalance
server.port=${PORT:8084}

# ?? Base de datos Neon ????????????????????????????????????????
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://ep-autumn-recipe-aqvjhsu1-pooler.c-8.us-east-1.aws.neon.tech/neondb?sslmode=require}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:neondb_owner}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:npg_1ioNfWVj9QXT}
spring.datasource.driver-class-name=org.postgresql.Driver

# ?? JPA / Hibernate ???????????????????????????????????????????
spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.datasource.hikari.maximum-pool-size=5

# ?? Mail ??????????????????????????????????????????????????????
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=${SPRING_MAIL_USERNAME:yudiguayara@gmail.com}
spring.mail.password=${SPRING_MAIL_PASSWORD:kutjqstavxqmouhk}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true

# ?? Notificaciones ????????????????????????????????????????????
notificacion.email.destinatario=${NOTIFICACION_EMAIL_DESTINATARIO:yudiguayara@gmail.com}
notificacion.email.habilitado=true